site_name: fromistory
hooks:
  - overrides/.hooks/sort_posts_latest.py
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: deep purple
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
#    - navigation.top
    - navigation.hide
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.prune
  font:
    text: Open Sans
    code: JetBrains Mono
  favicon: assets/fromis-logo-white.svg
  logo: assets/fromis-logo-white.svg
markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
nav:
  - index.md
#  - Events:
#      - events/index.md
#  - events/171129.md
#plugins:
#  - blog:
#      blog_dir: events
#      pagination: True
#      pagination_per_page: 1
#      blog_toc: True
#      post_readtime: false
#      post_date_format: MMMM d, yyyy hh:mm
#      post_url_format: "{slug}"
#      archive: false
#  - tags:
#      tags_file: events/tags.md